const router = require("express").Router();
const dealerRoutes = require("./dealerRoutes");
const masterRoutes = require("./masterRoutes");
const outletRoutes = require("./outletRoutes");
const employeeRoutes = require("./employeeRoutes");
const auth = require("../../../middlewares/adminAuth");
const dashboardRoutes = require("./dashboardRoutes");
const scoreRuleRoutes = require("./scoreRuleRoutes");
const scoreStageRoutes = require("./scoreStageRoutes");
const announcementRoutes = require("./announcementRoutes");
const staffRoutes = require("./staffRoutes");
const roleRoutes = require("./roleRoutes");
const moduleRoutes = require("./moduleRoutes");
const permissionRoutes = require("./permissionRoutes");
router.use("/dealers", auth, dealerRoutes);
router.use("/masters", auth, masterRoutes);
router.use("/outlets", auth, outletRoutes);
router.use("/employees", auth, employeeRoutes);
router.use("/dashboard", auth, dashboardRoutes);
router.use("/score-rules", auth, scoreRuleRoutes);
router.use("/score-stages", auth, scoreStageRoutes);
router.use("/announcements", auth, announcementRoutes);
router.use("/staff", auth, staffRoutes);
router.use("/roles", auth, roleRoutes);
router.use("/modules", auth, moduleRoutes);
router.use("/permissions", auth, permissionRoutes);
module.exports = router;
