const ExcelJS = require("exceljs");
const { buildPdf } = require("./pdfExportService");

function flattenRow(row) {
  if (!row || typeof row !== "object") return { value: row };
  const flat = {};
  for (const [key, value] of Object.entries(row)) {
    if (value && typeof value === "object" && !Array.isArray(value) && !(value instanceof Date)) {
      flat[key] = JSON.stringify(value);
    } else if (value instanceof Date) {
      flat[key] = value.toISOString();
    } else {
      flat[key] = value;
    }
  }
  return flat;
}

async function buildExcel(reportData) {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Report");

  sheet.addRow(["Report", reportData.meta.reportName]);
  sheet.addRow(["Generated At", reportData.meta.generatedAt]);
  sheet.addRow(["Generated By", reportData.meta.generatedBy?.name || ""]);
  if (reportData.meta.period) {
    sheet.addRow(["Period From", reportData.meta.period.from || ""]);
    sheet.addRow(["Period To", reportData.meta.period.to || ""]);
  }
  sheet.addRow([]);

  if (reportData.summary && Object.keys(reportData.summary).length) {
    sheet.addRow(["Summary"]);
    for (const [key, value] of Object.entries(reportData.summary)) {
      sheet.addRow([key, typeof value === "object" ? JSON.stringify(value) : value]);
    }
    sheet.addRow([]);
  }

  const rows = reportData.rows || [];
  if (rows.length) {
    const flatRows = rows.map(flattenRow);
    const headers = Object.keys(flatRows[0]);
    sheet.addRow(headers);
    for (const row of flatRows) {
      sheet.addRow(headers.map((h) => row[h] ?? ""));
    }
  }

  return workbook.xlsx.writeBuffer();
}

async function exportReport(reportData, format = "xlsx") {
  if (format === "pdf") {
    const buffer = await buildPdf(reportData);
    return {
      buffer,
      contentType: "application/pdf",
      filename: `${reportData.meta.reportKey}-${Date.now()}.pdf`,
    };
  }

  const buffer = await buildExcel(reportData);
  return {
    buffer,
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    filename: `${reportData.meta.reportKey}-${Date.now()}.xlsx`,
  };
}

module.exports = { exportReport, buildExcel, buildPdf };
