const express = require("express");
const router = express.Router();
const userRoutes = require("./userRoutes");
const contactPersonRoutes = require("./contactPersonRoutes");
const outletRoutes = require("./outletRoutes");
const employeeRoutes = require("./employeeRoutes");
const businessDocumentRoutes = require("./businessDocumentRoutes");
const masterRoutes = require("./masterRoutes");
const employerRoutes = require("./employerRoutes");
router.use("/user", userRoutes);
router.use("/contact-persons", contactPersonRoutes);
router.use("/outlets", outletRoutes);
router.use("/employees", employeeRoutes);
router.use("/business-documents", businessDocumentRoutes);
router.use("/masters", masterRoutes);
router.use("/employer-invitations", employerRoutes);
module.exports = router;