const express = require("express");
const router = express.Router();
const userRoutes = require("./userRoutes");
const contactPersonRoutes = require("./contactPersonRoutes");
const outletRoutes = require("./outletRoutes");
const employeeRoutes = require("./employeeRoutes");
const businessDocumentRoutes = require("./businessDocumentRoutes");
const masterRoutes = require("./masterRoutes");
const employerRoutes = require("./employerRoutes");
const employerLeavingRoutes = require("./employerLeavingRoutes");
const employeementTransferRoutes = require("./employeementTransferRoutes");
const commonRoutes = require("./commonRoutes");
const reportRoutes = require("./reportRoutes");
const staffRoutes = require("./staffRoutes");
const roleRoutes = require("./roleRoutes");
const moduleRoutes = require("./moduleRoutes");
const permissionRoutes = require("./permissionRoutes");
router.use("/user", userRoutes);
router.use("/contact-persons", contactPersonRoutes);
router.use("/outlets", outletRoutes);
router.use("/employees", employeeRoutes);
router.use("/business-documents", businessDocumentRoutes);
router.use("/masters", masterRoutes);
router.use("/employer-invitations", employerRoutes);
router.use("/employer-leaving", employerLeavingRoutes);
router.use("/employeement-transfer", employeementTransferRoutes);
router.use("/reports", reportRoutes);
router.use("/staff", staffRoutes);
router.use("/roles", roleRoutes);
router.use("/modules", moduleRoutes);
router.use("/permissions", permissionRoutes);
router.use("/", commonRoutes);
module.exports = router;